apiVersion: v1
kind: PersistentVolume
metadata:
  name: boomi-fsx-pv
spec:
  capacity:
    storage: 1200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fsx-sc
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-0202e48d7b528359c
    volumeAttributes:
      dnsname: fs-0202e48d7b528359c.fsx.us-west-2.amazonaws.com
      mountname: gyhcn
