apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: boomi-runtime-cluster-hpa
  labels:
    app: boomi-runtime-node
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: StatefulSet
    name: boomi-runtime-node
  minReplicas: 4
  maxReplicas: 20
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
